import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const ROUTES={
  'Wi-Fi / Internet':'IT / Network Team','Projector / AV':'IT / AV Support','Electricity':'Electrical Maintenance','Water / Leakage':'Plumbing / Civil','AC / HVAC':'HVAC Maintenance','Cleaning':'Housekeeping','Furniture':'Civil / Furniture Maintenance','Security':'Security Team','Other':'General Maintenance'
};
const STAFF=[
 {id:'it1',name:'Rahul Sharma',dept:'IT / Network Team',skill:'Network & Wi-Fi',available:true},
 {id:'elec1',name:'Amit Kumar',dept:'Electrical Maintenance',skill:'Electrical',available:true},
 {id:'plumb1',name:'Suresh Yadav',dept:'Plumbing / Civil',skill:'Plumbing',available:true},
 {id:'hvac1',name:'Neeraj Singh',dept:'HVAC Maintenance',skill:'AC / HVAC',available:true},
 {id:'clean1',name:'Pooja Verma',dept:'Housekeeping',skill:'Cleaning',available:true},
 {id:'civil1',name:'Vikas Gupta',dept:'Civil / Furniture Maintenance',skill:'Furniture',available:true},
];
const seed=[
 {id:'INC-1042',title:'Wi-Fi not working in Lab 3',category:'Wi-Fi / Internet',location:'Lab 3',description:'No internet connection on multiple systems.',student:'Arzoo Rani',studentId:'STU1024',affected:4,duration:2,safety:15,locationImportance:75,frequency:65,status:'Assigned',assignedDepartment:'IT / Network Team',assignedStaff:'Rahul Sharma',evidence:[],created:'Today, 10:42 AM',reports:4,verification:null},
 {id:'INC-1041',title:'Water leakage – Room 204',category:'Water / Leakage',location:'Room 204',description:'Leakage near ceiling and wall.',student:'Diya Agarwal',studentId:'STU1025',affected:12,duration:5,safety:60,locationImportance:70,frequency:90,status:'In Progress',assignedDepartment:'Plumbing / Civil',assignedStaff:'Suresh Yadav',evidence:[],created:'Yesterday, 2:15 PM',reports:8,verification:null},
 {id:'INC-1040',title:'Electrical leakage near corridor',category:'Electricity',location:'Block A Corridor',description:'Sparking noticed near switchboard.',student:'Gauri Gupta',studentId:'STU1026',affected:30,duration:1,safety:100,locationImportance:90,frequency:70,status:'Resolved',assignedDepartment:'Electrical Maintenance',assignedStaff:'Amit Kumar',evidence:[],created:'Yesterday, 9:20 AM',reports:3,verification:null},
];
function impact(x){const affected=Math.min(100,Math.max(0,(x.affected||1)*8));const safety=x.safety??50;const loc=x.locationImportance??60;const freq=x.frequency??40;const duration=Math.min(100,(x.duration||1)*15);return Math.round(affected*.30+safety*.30+loc*.15+freq*.15+duration*.10)}
function band(n){return n>=80?'Critical':n>=60?'High':n>=35?'Medium':'Low'}
function App(){
 const [role,setRole]=useState(null); const [page,setPage]=useState('dashboard'); const [incidents,setIncidents]=useState(seed); const [selected,setSelected]=useState(null); const [zoom,setZoom]=useState(null); const [toast,setToast]=useState('');
 const [form,setForm]=useState({title:'',category:'Wi-Fi / Internet',location:'',description:'',affected:1,duration:1,evidence:null});
 const showToast=m=>{setToast(m);setTimeout(()=>setToast(''),2500)};
 const stats=useMemo(()=>({total:incidents.length,reports:incidents.reduce((a,x)=>a+x.reports,0),open:incidents.filter(x=>!['Resolved','Closed'].includes(x.status)).length,critical:incidents.filter(x=>impact(x)>=80).length}),[incidents]);
 if(!role)return <Login onLogin={r=>{setRole(r);setPage('dashboard')}}/>;
 const current=selected?incidents.find(x=>x.id===selected):null;
 function update(id,patch){setIncidents(a=>a.map(x=>x.id===id?{...x,...patch}:x));}
 function submit(e){e.preventDefault();const dep=ROUTES[form.category];const st=STAFF.find(s=>s.dept===dep);const item={id:'INC-'+(1043+incidents.length),title:form.title,category:form.category,location:form.location,description:form.description,student:'Arzoo Rani',studentId:'STU1024',affected:Number(form.affected)||1,duration:Number(form.duration)||1,safety:form.category==='Electricity'?100:form.category==='Security'?85:50,locationImportance:form.location.toLowerCase().includes('lab')?80:60,frequency:40,status:'Assigned',assignedDepartment:dep,assignedStaff:st?.name||'Pending coordinator assignment',evidence:form.evidence?[form.evidence]:[],created:'Just now',reports:1,verification:null};setIncidents(a=>[item,...a]);setForm({title:'',category:'Wi-Fi / Internet',location:'',description:'',affected:1,duration:1,evidence:null});showToast(`Reported → ${dep}`);setPage('myissues')}
 const nav=role==='student'?[['dashboard','Overview'],['report','Report Issue'],['myissues','My Issues']]:role==='staff'?[['dashboard','My Work'],['incidents','Assigned Issues']]:[['dashboard','Overview'],['incidents','Incidents'],['analytics','Analytics'],['teams','Teams']];
 return <div className="app"><aside><div className="brand"><div className="logo">R</div><div><b>RESOLVA</b><small>Report. Resolve. Improve.</small></div></div><div className="rolepill">{role==='student'?'🎓 Student':role==='staff'?'🛠️ Maintenance Staff':'🛡️ Admin'}</div><nav>{nav.map(([p,l])=><button className={page===p?'active':''} onClick={()=>setPage(p)} key={p}>{icon(l)}<span>{l}</span></button>)}</nav><div className="sidebar-note"><b>Smart Routing</b><p>Complaints are routed to the responsible maintenance team. Admin monitors, assigns and escalates.</p></div><button className="logout" onClick={()=>setRole(null)}>↩ Logout</button></aside>
 <main><header><div><div className="eyebrow">INTELLIGENT CAMPUS ISSUE RESOLUTION</div><h1>{role==='student'?'Student Workspace':role==='staff'?'Maintenance Workbench':'Operations Command Center'}</h1></div><div className="top-actions"><span className="live">● System Live</span><div className="avatar">{role[0].toUpperCase()}</div></div></header>
 {page==='dashboard'&&<Dashboard role={role} stats={stats} incidents={incidents} onOpen={setSelected} onPage={setPage}/>} 
 {page==='report'&&<Report form={form} setForm={setForm} submit={submit}/>} 
 {page==='myissues'&&<IssueList incidents={incidents.filter(x=>x.studentId==='STU1024')} onOpen={setSelected} student onZoom={setZoom}/>} 
 {page==='incidents'&&<IssueList incidents={role==='staff'?incidents.filter(x=>x.assignedStaff==='Rahul Sharma'||x.assignedDepartment):incidents} onOpen={setSelected} admin={role==='admin'} onUpdate={update} onZoom={setZoom}/>} 
 {page==='analytics'&&<Analytics incidents={incidents}/>} 
 {page==='teams'&&<Teams incidents={incidents}/>} 
 </main>
 {current&&<Detail x={current} role={role} close={()=>setSelected(null)} update={update} onZoom={setZoom}/>} {zoom&&<ImageModal src={zoom} close={()=>setZoom(null)}/>} {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}
function icon(l){return l==='Overview'?'⌂':l.includes('Report')?'＋':l.includes('Issue')||l==='Incidents'||l==='Assigned Issues'?'▣':l==='Analytics'?'◒':'♙'}
function Login({onLogin}){return <div className="login"><div className="login-card"><div className="login-brand"><div className="logo big">R</div><div><h1>RESOLVA</h1><p>Intelligent Campus Issue Resolution Platform</p></div></div><div className="hero"><span>SMART • VERIFIED • PREDICTIVE</span><h2>From scattered complaints<br/>to actionable campus incidents.</h2><p>Similarity + location + history + impact + verification</p></div><div className="login-grid"><button onClick={()=>onLogin('student')}><span>🎓</span><b>Student Login</b><small>Report, track & verify issues</small></button><button onClick={()=>onLogin('admin')}><span>🛡️</span><b>Admin Login</b><small>Monitor, assign & escalate</small></button><button onClick={()=>onLogin('staff')}><span>🛠️</span><b>Maintenance Staff</b><small>Work on assigned complaints</small></button></div><small className="demo">Demo prototype • Role-based access</small></div></div>}
function Dashboard({role,stats,incidents,onOpen,onPage}){const avg=Math.round(incidents.reduce((a,x)=>a+impact(x),0)/incidents.length);return <section className="page"><div className="welcome"><div><span className="tag">LIVE CAMPUS INTELLIGENCE</span><h2>{role==='student'?'Good to see you again 👋':role==='staff'?'Your assigned work, in one place.':'Campus overview at a glance.'}</h2><p>{role==='student'?'Raise an issue with evidence and follow its complete resolution journey.':'RESOLVA connects student reports to responsible teams, measurable impact and verified resolution.'}</p></div>{role==='student'&&<button className="primary" onClick={()=>onPage('report')}>＋ Report an Issue</button>}</div><div className="stats"><Stat n={stats.total} l="Campus Incidents"/><Stat n={stats.reports} l="Linked Reports"/><Stat n={stats.open} l="Open / Active"/><Stat n={stats.critical} l="Critical Impact" danger/></div><div className="grid2"><div className="card"><div className="cardhead"><div><h3>Priority Queue</h3><p>System-calculated campus impact</p></div><span className="mini">No manual score</span></div>{incidents.sort((a,b)=>impact(b)-impact(a)).slice(0,4).map(x=><div className="issue-row" key={x.id} onClick={()=>onOpen(x.id)}><div className="issue-icon">{catIcon(x.category)}</div><div className="grow"><b>{x.title}</b><span>{x.location} · {x.assignedDepartment}</span></div><strong className="score">{impact(x)}<small>/100</small></strong><span className={'badge '+band(impact(x)).toLowerCase()}>{band(impact(x))}</span></div>)}</div><div className="card intelligence"><div className="cardhead"><div><h3>RESOLVA Intelligence</h3><p>What the system is doing</p></div>⚡</div><div className="flow"><Flow n="1" t="Report + Evidence"/><Flow n="2" t="Similarity & Location"/><Flow n="3" t="Impact Calculation"/><Flow n="4" t="Smart Routing"/><Flow n="5" t="Repair → Verify"/></div><div className="impact-box"><b>Campus Impact Score</b><div className="weights"><span>Affected 30%</span><span>Safety 30%</span><span>Location 15%</span><span>Frequency 15%</span><span>Duration 10%</span></div><small>Final score is calculated by the system — students and admins do not type it.</small></div></div></div></section>}
const Stat=({n,l,danger})=><div className={'stat '+(danger?'danger':'')}><strong>{n}</strong><span>{l}</span></div>;const Flow=({n,t})=><div className="flowitem"><i>{n}</i><span>{t}</span></div>;
function Report({form,setForm,submit}){return <section className="page"><div className="sectiontitle"><div><span className="tag">STUDENT REPORT</span><h2>Tell RESOLVA what happened</h2><p>Only factual inputs are collected. Impact Score is calculated automatically.</p></div></div><form className="report-card" onSubmit={submit}><div className="form-grid"><label>Issue title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Wi-Fi not working in Lab 3"/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{Object.keys(ROUTES).map(x=><option key={x}>{x}</option>)}</select></label><label>Location<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Lab / Room / Block"/></label><label>Duration (days)<input type="number" min="1" max="30" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><label className="full">Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe the issue clearly..."/></label><label>Affected people (estimate)<input type="number" min="1" value={form.affected} onChange={e=>setForm({...form,affected:e.target.value})}/><small>This is only reported evidence; it is not the Impact Score.</small></label><div className="upload"><span>📷</span><div><b>Photo / Evidence</b><small>Camera or gallery supported</small></div><input type="file" accept="image/*" capture="environment" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setForm({...form,evidence:r.result});r.readAsDataURL(f)}}/></div></div>{form.evidence&&<div className="preview"><img src={form.evidence}/><span>Evidence attached ✓</span></div>}<div className="routing-preview"><b>Smart routing:</b> {ROUTES[form.category]} <span>→</span> available skilled staff will be suggested.</div><button className="primary wide">Submit Complaint →</button></form></section>}
function IssueList({incidents,onOpen,student,onUpdate,onZoom}){return <section className="page"><div className="sectiontitle"><div><span className="tag">{student?'MY REPORTS':'OPERATIONS'}</span><h2>{student?'Track your issues':'Incident Management'}</h2><p>{student?'Tap an evidence photo to open it full-screen.':'Every incident shows reporter, evidence, routing and calculated impact.'}</p></div></div><div className="list">{incidents.map(x=><div className="card incident-card" key={x.id} onClick={()=>onOpen(x.id)}><div className="incident-top"><div><span className="id">{x.id}</span><h3>{x.title}</h3><p>📍 {x.location} · 👤 {x.student} · {x.created}</p></div><span className={'status '+x.status.toLowerCase().replace(' ','-')}>{x.status}</span></div><div className="incident-meta"><span>🔀 {x.reports} linked reports</span><span>🛠 {x.assignedDepartment}</span><span>🎯 Impact <b>{impact(x)}/100</b></span></div>{x.evidence?.length>0&&<div className="thumbs">{x.evidence.map((src,i)=><img key={i} src={src} onClick={e=>{e.stopPropagation();onZoom(src)}}/>)}<span>Tap photo to enlarge</span></div>}{student&&x.status==='Resolved'&&<div className="verifyline"><b>Resolution needs your verification</b><button onClick={e=>{e.stopPropagation();onUpdate?.(x.id,{status:'Closed',verification:'Fixed'})}}>✓ Confirm Fixed</button><button className="ghost" onClick={e=>{e.stopPropagation();onUpdate?.(x.id,{status:'Reopened',verification:'Still Occurring'})}}>↻ Still Occurring</button></div>}</div>)}</div></section>}
function Detail({x,role,close,update,onZoom}){const staff=STAFF.filter(s=>s.dept===x.assignedDepartment);return <div className="overlay" onClick={close}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="drawer-head"><span className="id">{x.id}</span><h2>{x.title}</h2><p>📍 {x.location} · Reported by <b>{x.student}</b> ({x.studentId})</p></div><div className="scorehero"><div><small>Campus Impact Score</small><strong>{impact(x)}<em>/100</em></strong><span className={'badge '+band(impact(x)).toLowerCase()}>{band(impact(x))} Impact</span></div><div className="scorebars"><span>Affected 30%</span><span>Safety 30%</span><span>Location 15%</span><span>Frequency 15%</span><span>Duration 10%</span></div></div><div className="detailgrid"><div><h4>Evidence</h4>{x.evidence?.length?<div className="bigthumbs">{x.evidence.map((s,i)=><img key={i} src={s} onClick={()=>onZoom(s)}/>)}</div>:<div className="empty">No photo attached</div>}</div><div><h4>Smart Routing</h4><div className="route"><b>{x.assignedDepartment}</b><span>Assigned staff: {x.assignedStaff||'Pending'}</span><small>Category: {x.category}</small></div></div></div><div className="timeline"><Step done t="Student Reported"/><Step done t="Intelligence Analysed"/><Step done t={`Routed → ${x.assignedDepartment}`}/><Step done={['In Progress','Resolved','Closed'].includes(x.status)} t={x.status==='Assigned'?'Awaiting Staff Action':'Repair / Work in Progress'}/><Step done={['Closed'].includes(x.status)} t="Student Verification"/></div>{role==='admin'&&<div className="assign"><h4>Admin Controls</h4><label>Responsible staff<select value={x.assignedStaff||''} onChange={e=>update(x.id,{assignedStaff:e.target.value,status:'Assigned'})}><option value="">Select staff</option>{staff.map(s=><option key={s.id}>{s.name}</option>)}</select></label><div className="btnrow"><button onClick={()=>update(x.id,{status:'In Progress'})}>Start / Assign</button><button onClick={()=>update(x.id,{status:'Resolved'})}>Mark Resolved</button></div></div>}{role==='staff'&&<div className="assign"><h4>Maintenance Action</h4><p>Inspect the issue, perform the repair, then update status.</p><div className="btnrow"><button onClick={()=>update(x.id,{status:'In Progress'})}>▶ Start Work</button><button onClick={()=>update(x.id,{status:'Resolved'})}>✓ Mark Resolved</button></div></div>}</div></div>}
const Step=({done,t})=><div className={done?'done':''}><i>{done?'✓':'○'}</i><span>{t}</span></div>;
function ImageModal({src,close}){return <div className="image-overlay" onClick={close}><div className="image-view"><button onClick={close}>×</button><img src={src}/><span>Click anywhere to close</span></div></div>}
function Analytics({incidents}){const cats={};incidents.forEach(x=>cats[x.category]=(cats[x.category]||0)+1);return <section className="page"><div className="sectiontitle"><div><span className="tag">DATA & INSIGHTS</span><h2>Campus Analytics</h2><p>Interactive view of incidents, routing and impact.</p></div></div><div className="analytics-grid"><div className="card"><h3>Impact Distribution</h3>{incidents.map(x=><div className="barrow" key={x.id}><span>{x.title.slice(0,24)}</span><div><i style={{width:`${impact(x)}%`}}/></div><b>{impact(x)}</b></div>)}</div><div className="card"><h3>Smart Routing Load</h3>{Object.entries(cats).map(([k,v])=><div className="load" key={k}><div><span>{k}</span><b>{v}</b></div><div className="track"><i style={{width:`${Math.min(100,v*25)}%`}}/></div><small>{ROUTES[k]}</small></div>)}</div></div><div className="card health"><h3>Campus Health Score <strong>78 / 100</strong></h3><p>Summary signal based on issue volume, severity, recurrence and resolution patterns.</p></div></section>}
function Teams({incidents}){return <section className="page"><div className="sectiontitle"><div><span className="tag">MAINTENANCE NETWORK</span><h2>Teams & Resource Board</h2><p>Admin coordinates; responsible teams perform the actual repair.</p></div></div><div className="teamgrid">{STAFF.map(s=><div className="card team" key={s.id}><div className="person">{s.name[0]}</div><div><h3>{s.name}</h3><p>{s.dept}</p><span>{s.skill}</span></div><b className="available">● Available</b><small>Active assignments: {incidents.filter(x=>x.assignedStaff===s.name&&!['Closed'].includes(x.status)).length}</small></div>)}</div></section>}
function catIcon(c){return c==='Electricity'?'⚡':c.includes('Water')?'💧':c.includes('Wi-Fi')?'📶':c.includes('AC')?'❄️':c==='Cleaning'?'🧹':c==='Security'?'🛡️':'🔧'}
createRoot(document.getElementById('root')).render(<App/>);
